### ISSUE TITLE
Keskustelupalsta

### ISSUE THREAD

**Issue by minnasiivo** [OonaPolsa/Projekti1#7]
Aika-arvio: 6 päivää

https://javascript.plainenglish.io/how-to-create-a-discussion-forum-using-angular-and-firebase-6f6f30d4fb9c

**Comment by OonaPolsa** [comment]
Vaatii back-end yhteyden toimiakseen alkuperäisen suunnitelman mukaisesti. Nyt käytössä vain kokeiluversio.
